apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -main

resources:
  - ansible-stream.yaml
  - rhtas-operator-stream.yaml
  - tas-components-stream.yaml
  - tas-tools-stream.yaml
configurations:
  - kustomizeconfig.yaml

