apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -v1-2

resources:
  - rhtas-operator-stream.yaml
  - tas-components-stream.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - path: patch/mintmaker.yaml
    target:
      kind: ProjectDevelopmentStream 
