apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - overlay/ansible
  - overlay/rekor-monitor
  - overlay/rhtas-fbc
  - overlay/rhtas-operator
  - overlay/segment-backup-job
  - overlay/tas-tools
  - overlay/tas-components
  - overlay/create-tree
  - overlay/client-server
  - overlay/tough
  - overlay/policy-controller
  - overlay/policy-controller-operator
