apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - template.yaml

components:
  - ../../../project/base/ec
  - ../../../project/base/release-plan

patches:
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/trillian-database.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/segment-backup.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/certificate-transparency-go.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/fulcio-server.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/rekor-monitor.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/rekor-search.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/rekor-server.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/timestamp-authority.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/trillian-createtree.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/trillian-logserver.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/trillian-logsigner.yaml
  - target:
      name: tas-components-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/trillian-redis.yaml
