apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - template.yaml

components:
  - ../../../project/base/ec
  - ../../../project/base/monorepo
  - ../../../project/base/release-plan

patches:
  - target:
      name: operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/manager.yaml
  - target:
      name: operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/bundle.yaml
  - target:
      name: operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/e2e.yaml
