apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - template.yaml

components:
  - ../../base/ec
  - ../../base/release-plan

patches:
  - target:
      name: segment-backup-job-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/segment-backup-job.yaml