apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -main

components:
  - ../../base/

configurations:
  - kustomizeconfig.yaml

patches:
  - path: patch/ansible-template-ref.yaml
  - path: patch/operator-template-ref.yaml
  - path: patch/tas-components-template-ref.yaml
  - path: patch/tas-tools-template-ref.yaml

