apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -main

components:
  - ../../base/

configurations:
  - kustomizeconfig.yaml

patches:
  - patch: |
      - op: add
        path: /spec/tenantPipeline/params/-
        value:
          name: revision
          value: "RHTAS-build-bot_candidate-images-main"
    target:
      kind: ReleasePlan
      labelSelector: "build.rhtas.com/release-plan=promote-to-candidate"
