apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pco-fbc-v4-16.yaml
  - pco-fbc-v4-17.yaml
  - pco-fbc-v4-18.yaml
  - pco-fbc-v4-19.yaml
  - pco-fbc-v4-20.yaml
  - pco-fbc-v4-21.yaml
