apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -v1-3

components:
  - ../../base/

configurations:
  - kustomizeconfig.yaml

patches:
  - path: patch/stream.yaml
    options:
      allowNameChange: false
    target:
      kind: ProjectDevelopmentStream
  - patch: |
      - op: add
        path: /spec/tenantPipeline/params/-
        value:
          name: revision
          value: "RHTAS-build-bot_candidate-images-v1.3"
    target:
      kind: ReleasePlan
      labelSelector: "build.rhtas.com/release-plan=promote-to-candidate"
