apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pco-fbc-v4-16-tech-preview.yaml
  - pco-fbc-v4-17-tech-preview.yaml
  - pco-fbc-v4-18-tech-preview.yaml
  - pco-fbc-v4-19-tech-preview.yaml
  - pco-fbc-v4-20-tech-preview.yaml
  - pco-fbc-v4-21-tech-preview.yaml
