apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - template.yaml

components:
  - ../../base/ec
  - ../../base/release-plan

patches:
  - target:
      name: policy-controller-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/policy-controller.yaml
  - target:
      name: policy-controller-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/releaseplan.yaml
