apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component


resources:
  - ansible-stream.yaml
  - rekor-monitor-stream.yaml
  - rhtas-operator-stream.yaml
  - segment-backup-job-stream.yaml
  - tas-tools-stream.yaml
  - tough-stream.yaml