apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: namespace-wide-nudging-renovate-config
    literals:
      - automerge="true"
      - platformAutomerge="true"
