apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Konflux components
  - konflux/base
  - pipelines/base
  # RHTAS components
  - cli/base
  - model-transparency/base
  - model-validation-operator/base
  - policy-controller/base
  - policy-controller-operator/base
  - rhtas-console/base
