apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhtas-tenant

resources:
  - ../../base/service-account
  - ../../base/release-plan
  - ../../base/application
  - ../../base/project
  - ../../base/stream
  - ../../base/config

# Prod environment already uses quay.io/securesign prefix in base
# No patches needed
