apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -v1-2

components:
  - ../../base/

configurations:
  - kustomizeconfig.yaml

patches:
  - path: patch/stream.yaml
    options:
      allowNameChange: false
    target:
      kind: ProjectDevelopmentStream
  - path: patch/mintmaker.yaml
    target:
      kind: ProjectDevelopmentStream
  - path: patch/exclude-rekor-monitor.yaml