apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - template.yaml

components:
  - ../../base/ec
  - ../../base/release-plan

patches:
  - target:
      name: policy-controller-operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/manager.yaml
  - target:
      name: policy-controller-operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/imagerepository.yaml
  - target:
      name: policy-controller-operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/bundle.yaml
  - target:
      name: policy-controller-operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/e2e.yaml
  - target:
      name: policy-controller-operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/releaseplan.yaml
