apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  # For operator-type templates (rhtas-operator, ansible)
  - target:
      kind: ProjectDevelopmentStreamTemplate
      labelSelector: "build.rhtas.com/type in (operator, ansible)"
    path: patch/operator.yaml

  # For component-type templates (rekor-monitor, etc.)
  - target:
      kind: ProjectDevelopmentStreamTemplate
      labelSelector: "build.rhtas.com/type=component"
    path: patch/component.yaml
